baseURL = "https://equiden-therapie.github.io/"
languageCode = "de-de"
theme = "radiation"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Equitron"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Mehr infos"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Buchen"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "Equitron"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Mehr infos"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Buchen"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about", "client-and-work", "contact"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Equiden Therarpie"
    text2 = "Härke"

  [params.footer]
      copyright = "© Equiden Therapie - Härke. Alle rechte vorbehalten."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
