baseURL = "https://equiden-therapie.github.io/"
languageCode = "de-de"
theme = "raditian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
  [menu]

  [[menu.header]]
  name = "Equitron"
  URL = "#equitron"
  weight = 2

  [[menu.header]]
  name = "Mehr infos"
  URL = "#infos"
  weight = 3

  [[menu.header]]
  name = "Buchen"
  URL = "#buchung"
  weight = 4


  [[menu.footer]]
  name = "Equitron"
  URL = "#equitron"
  weight = 2

  [[menu.footer]]
  name = "Mehr infos"
  URL = "#infos"
  weight = 3

  [[menu.footer]]
  name = "Buchen"
  URL = "#buchung"
  weight = 4

  [[menu.footer]]
  name = "Datenschutz"
  URL = "datenschutz"
  weight = 5

[params]

  sections = ["showcase", "about", "client-and-work", "contact"]

  [params.logo]
    text1 = "EquiHealth"
    text2 = "Härke"
    [params.logo.icon]
      url = "img/icon.svg"
      alt = "EquiHealth logo"

  [params.footer]
      copyright = "© EquiHealth - Härke. Alle rechte vorbehalten."
      [params.footer.radity_logo]
        x = "img/icon-white.svg"
        _2x = "img/icon-white.svg"
        alt = "EquiHealth icon"
        url = "#"
